### ISSUE TITLE
Error in etf_preprocessing.py

### ISSUE THREAD

**Issue by eduardomsjr** [KingLear194/BlackLittermanEnd2End#3]
When I try to run the script src/etf_preprocessing.py, the following error occurs:

[root@slurmctld BlackLittermanEnd2End]# python3 src/etf_preprocessing.py 
Started Preprocessing for project etf.

Saving benchmark covariances as a dict for loading to computing units.
Traceback (most recent call last):
  File "/data/BlackLittermanEnd2End/src/etf_preprocessing.py", line 316, in <module>
    exec_preprocessing()
  File "/data/BlackLittermanEnd2End/src/etf_preprocessing.py", line 295, in exec_preprocessing
    train_utils.pickle_covs(cov_path = f"{settings.datapath}/final/{project_name}_b_{nr}fac/", 
  File "/data/BlackLittermanEnd2End/src/train_utils.py", line 158, in pickle_covs
    with open(savepath, "wb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/data/BL-End2End/Data/current_train_val_test/etf/etf_b_3fac_dict'`

Could you please provide more information about how overcome this error? 

Grateful for the attention.

**Comment by KingLear194** [comment]
The error is a FileNotFoundError, i.e. you do not have the folder structure with data as required by the code. For obvious reasons, you will have to change all the paths in the code to your local machine paths, where your own data are saved. Also, we cannot provide the data from the paper publicly because they are furnished by an academic database (TAQ) that prohibits public access.
