### ISSUE TITLE
The question about penalizing deviations for the views

### ISSUE THREAD

**Issue by YorkLouis** [KingLear194/BlackLittermanEnd2End#4]
<img width="501" alt="微信图片_20240730120418" src="https://github.com/user-attachments/assets/443ac08c-f0ca-4f25-937f-9731c123769b">
In BL model, does the posterior return (\mu_bl) have to satisfy the view return equation (P\mu_bl=Q) ?  In fact, the implied return (\mu) in equation P\mu=Q is a New Information of bayesian update, which is different from posterior estimation (\mu_bl). So is the penalty reasonable?

**Comment by KingLear194** [comment]
The classical BL model does not use a generalized distance as expressed here in the equation, but rather the Bayes rule, i.e. the posterior distribution of the benchmark excess return distributions conditional on the views being satisfied. This formula here is something else. It is related to the extension of the BL model in the spirit of Meucci et al (see the paper "Portfolio Construction and Systematic Trading with Factor Entropy Pooling" from Meucci, Ardia, Colasante; see also page 105 in paper "Black-Litterman and beyond" from Kolm, Ritter, Simonian). In this type of extension one minimizes another probability distance than the one that delivers Bayes rule. 
So theoretically speaking, here the constraint is that the distribution to be found in the distance-minimization problem needs to satisfy the views: P\mu = q. Why would you want to use such a more general model in principle? Besides the reasons mentioned in those papers, there may also exist practical reasons: e.g. if you are looking at an asset universe that is naturally unbalanced over time, e.g. corporate bonds in the US or EU, which even for the same issuer have different maturities, are issued at different dates etc. In such setups, I don't see a way to apply the Bayes rule approach in an end-to-end approach as is the focus of the paper. One does not even have the same covariance matrix for the whole horizon, because of dataset imbalance (assets coming and going). But with the general distance minimization and the factor approximation to the covariance matrix in the formula, one can train a model for the case of imbalanced datasets as well (whether one should bother doing such a thing depending on application is another issue).
 
Now why the Lagrange multiplier in the formula above? Numerically, in a neural-networks framework with Pytorch, I didn't find a good way to model the constraint P\mu=q in its strong form, so the Lagrange multiplier approach is an easy way to have the constraint in the optimization problem, albeit now only ''weakly'' satisfied. 
Hope this helps!

**Comment by YorkLouis** [comment]
Thanks for your detailed reply.
